### ISSUE TITLE
"ValueError: operands could not be broadcast together with shapes" - after running for some frames

### ISSUE THREAD

**Issue by vj68** [sparrowml/pytorch-object-tracking#3]
```bash
Traceback (most recent call last):
  File "main.py", line 133, in <module>
    track(video_path, output_path, threshold, class_index)
  File "main.py", line 75, in track
    cost = np.linalg.norm(prev_boxes[:, None] - boxes[None], axis=-1)
ValueError: operands could not be broadcast together with shapes (0,1) (1,5,4)
```

**Comment by jbencook** [comment]
Thanks for the heads up @rajvijay68! I don't have it very well documented, but I plan to keep [this package](https://github.com/sparrowml/tracky) more up-to-date if you want to take a look.

**Comment by vj68** [comment]
Thank you @jbencook.
